#!/usr/bin/env bash
#display numbers 1-100, FIzzBUZZ multible of 3 and 5, Fizz mul of 3, Buzz mull of 5
i=1;
while ((i <= 100));
do
	if ((i%15 == 0)); then
	echo "FizzBuzz"
	elif ((i%3 == 0)); then
	echo "Fizz"
	elif ((i%5 == 0)); then
	echo "Buzz"
	else
	echo "$i"
	fi
	((i++))
done
