#!/usr/bin/env bash
# This Script displays "Best School" 10 times but on the ninth time, it adds a hi

i=1
while ((i <= 10));
do
	echo "Best School"
	if ((i == 9)); then
	echo "Hi"
	fi
	((i++));
done
